# Generated by Django 4.2 on 2023-05-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_usedpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedpassword',
            name='ip_address',
            field=models.CharField(default='1.1.1.1', max_length=100),
            preserve_default=False,
        ),
    ]
